export type FAQ = { q: string; a: string };
export type Service = {
  slug: string; shortTitle: string; title: string; priority: number; icon: string;
  summary: string; intro: string; method: string; benefits: string[]; includes: string[];
  surfaces: string[]; faqs: FAQ[]; category?: ServiceCategory; release?: "live"|"draft";
  relatedServices?: string[];
};
export type ServiceCategory = "exterior-cleaning"|"complete-exterior-maintenance"|"commercial";

const currentServices: Service[] = [
  { slug:"house-washing-kilmore", shortTitle:"House Washing", title:"House Washing in Kilmore & Mitchell Shire", priority:1, icon:"⌂", summary:"Appropriate soft washing for cladding, render, brick, eaves and exterior walls.", intro:"Dust, mould, algae, cobwebs and traffic film gradually dull a home’s exterior. Our house washing service restores a cleaner, fresher finish using a method selected for the actual wall system, not a one pressure approach.", method:"We inspect the coating, substrate, access, plants, electrical points and water sensitive openings before work begins. Painted and delicate finishes are cleaned with low pressure and an appropriate treatment, while stubborn areas receive targeted agitation. Render and coated cladding are kept within appropriate pressure limits. We rinse thoroughly and protect surrounding areas throughout the job.", benefits:["Refresh the entire exterior","Treat organic growth at its source","Protect delicate coatings with controlled pressure","Improve presentation before selling or painting"], includes:["Exterior walls and cladding","Exterior gutters, fascia and accessible eaves","Cobweb and surface growth removal","Initial assessment and thorough rinse"], surfaces:["Weatherboard and Weathertex","Painted brick","Rendered and textured finishes","Colorbond wall cladding"], faqs:[{q:"Is house washing the same as pressure washing?", a:"No. House washing usually relies on controlled low pressure, appropriate cleaning treatments and gentle rinsing. Hard flat surfaces generally require a different pressure cleaning process."},{q:"Will you use high pressure on render?", a:"No. Render and texture coatings are assessed carefully and cleaned at controlled pressure to reduce the risk of damage."},{q:"How often should a house be washed?", a:"Exposure, shade, surrounding trees and coating type all affect the interval. Many manufacturers recommend regular inspection and periodic cleaning rather than waiting for heavy growth."}]},
  { slug:"roof-cleaning-kilmore", shortTitle:"Roof Cleaning", title:"Roof Cleaning & Biocide Treatment in Kilmore", priority:2, icon:"⌃", summary:"Roof soft washing and biocide treatments tailored to tile and Colorbond roofing.", intro:"Moss, lichen, algae and airborne grime can make roofing look tired and hold moisture against the surface. We provide considered roof cleaning options for suitable tile and Colorbond roofs across Kilmore and the Mitchell Shire.", method:"Roof access, pitch, material, coating condition, water tanks and drainage are assessed first. The method may involve soft washing, targeted organic growth treatment or a biocide application that works over time. Colorbond, concrete tile and terracotta each require different limits and precautions. Rainwater tank lines are isolated where required, and runoff is managed as part of the job plan.", benefits:["Treat moss, algae and lichen","Use a roof material specific method","Improve overall roof presentation","Plan for tanks, runoff and surrounding property"], includes:["Roof and access assessment","Soft wash or biocide option","Material appropriate application","Careful rinse or leave on treatment as specified"], surfaces:["Colorbond roofing","Concrete roof tiles","Terracotta tiles where suitable","Associated fascia and gutters by quote"], faqs:[{q:"Do you pressure wash every roof?", a:"No. Soft washing or a biocide treatment is often more suitable. We select the method after assessing the roof material and condition."},{q:"What is a biocide treatment?", a:"It is a targeted treatment for biological growth that can continue working after application. Results and timing vary with the roof and weather."},{q:"What happens if I have rainwater tanks?", a:"Tank connections and runoff must be considered before roof cleaning. We discuss the necessary isolation and reconnection steps during the quote."}]},
  { slug:"surface-pressure-washing-kilmore", shortTitle:"Surface Pressure Washing", title:"Surface Pressure Washing in Kilmore & Mitchell Shire", priority:3, icon:"≈", summary:"Professional cleaning for driveways, paths, patios, exposed aggregate, pavers and decks.", intro:"Flat outdoor surfaces collect traffic film, soil, organic growth, tyre marks and staining. We use professional pressure cleaning equipment and surface specific preparation to produce a consistent clean across residential and commercial properties.", method:"We identify the substrate, coating or sealer, condition and stain type before selecting pressure, nozzle angle and cleaning treatment. Concrete and exposed aggregate are cleaned in controlled overlapping passes. Timber decks receive a dedicated timber safe process with suitable cleaners, careful dwell times and a thorough rinse, never treated like concrete. Stain removal and resealing are assessed separately.", benefits:["Restore driveways and paths","Clean decks with a timber specific method","Use even passes for a consistent finish","Prepare suitable surfaces for resealing"], includes:["Concrete and driveway cleaning","Paths, pavers and patios","Exposed aggregate","Timber deck cleaning"], surfaces:["Concrete","Exposed aggregate","Brick and concrete pavers","Timber decking"], faqs:[{q:"Can pressure washing damage concrete?", a:"Poor technique can. We select pressure, nozzle and distance for the surface and avoid close range or sharp angle cleaning that may pit concrete or dislodge aggregate."},{q:"Is deck cleaning included?", a:"Yes. Deck cleaning sits within our surface pressure washing service, but uses a timber specific process rather than standard concrete pressure."},{q:"Can you remove rust and oil?", a:"Many surface stains can be improved with targeted treatment. We first identify the stain and substrate because internal ironstone, transferred rust and deeply absorbed oil require different expectations."}]},
  { slug:"gutter-cleaning-kilmore", shortTitle:"Gutter Cleaning", title:"Gutter Cleaning in Kilmore & Mitchell Shire", priority:4, icon:"⌁", summary:"Remove leaves, mud and debris so gutters and downpipes can drain properly.", intro:"Blocked gutters can overflow into eaves, walls and foundations. Our gutter cleaning service removes built up leaves, mud, nests and debris from homes and suitable commercial properties throughout the region.", method:"We assess roof access, pitch, gutter condition and surrounding hazards. The gutter line is cleared thoroughly, accessible downpipes are checked for flow and removed debris is collected from the property. We work carefully around roofing, flashing, solar equipment and rainwater systems.", benefits:["Help prevent gutter overflow","Reduce risky DIY ladder work","Keep drainage paths clear","Protect presentation around the roofline"], includes:["Gutter debris removal","Accessible valley clearing","Downpipe flow check","Work area clean up"], surfaces:["Residential gutters","Suitable commercial gutters","Roof valleys by assessment","Gutter exterior cleaning by quote"], faqs:[{q:"How often should gutters be cleaned?", a:"Many homes benefit from cleaning once or twice a year. Properties around mature trees may need a shorter interval."},{q:"Do you remove the debris?", a:"Yes. We collect the material we remove rather than leaving it scattered around the property."},{q:"Can you clean gutter exteriors too?", a:"Yes, exterior gutter soft washing can be quoted as a separate service."}]},
  { slug:"solar-panel-cleaning-kilmore", shortTitle:"Solar Panel Cleaning", title:"Solar Panel Cleaning in Kilmore & Mitchell Shire", priority:5, icon:"☼", summary:"Gentle panel cleaning based on manufacturer safe water, tools and access practices.", intro:"Dust, pollen, bird droppings and regional airborne grime can build up across solar arrays. We clean suitable systems carefully without abrasive blades, harsh chemicals or inappropriate pressure.", method:"We assess panel access, roof safety, weather and panel condition. Cleaning is scheduled away from excessive panel heat where practical and uses soft, gentle equipment with suitable water and mild cleaning products where permitted. We never make unrealistic energy output promises and do not interfere with electrical components.", benefits:["Remove dust and bird residue","Avoid abrasive DIY tools","Follow conservative manufacturer principles","Improve the system’s appearance"], includes:["Access and safety assessment","Gentle panel surface cleaning","Non abrasive equipment","Residential and suitable commercial arrays"], surfaces:["Common framed solar modules","Residential arrays","Suitable commercial arrays","Accessible ground mounted panels"], faqs:[{q:"Will cleaning increase output?", a:"Removing material that blocks sunlight may help, but the change depends on the system, soiling, orientation and other factors. We do not guarantee a specific performance increase."},{q:"Do you pressure wash solar panels?", a:"No. We use gentle methods consistent with conservative manufacturer guidance."},{q:"When is the best time to clean panels?", a:"Cooler conditions such as morning or overcast periods are generally preferable to cleaning hot panels in direct sun."}]},
  { slug:"basic-window-cleaning-kilmore", shortTitle:"Basic Window Cleaning", title:"Basic Window Cleaning in Kilmore & Mitchell Shire", priority:6, icon:"◇", summary:"Straightforward residential and commercial glass cleaning for a clearer finish.", intro:"Our basic window cleaning service is designed for routine dirt, dust and light marks on accessible residential and commercial glazing. It is a practical addition to exterior cleaning or a simple standalone service.", method:"We use standard professional window cleaning tools and suitable water based products to clean glass to a clear finish. The service is intentionally basic and does not include specialist restoration, hard water correction, construction debris or extensive track detailing unless specifically assessed and quoted.", benefits:["Clear routine grime from glass","Brighten rooms and improve presentation","Combine with another exterior service","Straightforward scope and expectations"], includes:["Basic exterior glass cleaning","Basic interior glass by arrangement","Accessible frames and sills","Routine residential or commercial windows"], surfaces:["Standard household glass","Shopfront glass where suitable","Accessible internal glass","Exterior windows within safe access"], faqs:[{q:"What does basic window cleaning include?", a:"It covers routine glass cleaning. Specialist stain restoration, construction cleaning, heavy scraping, detailed tracks and damaged glass are outside the basic scope."},{q:"Do you clean inside and outside?", a:"Exterior only or interior and exterior cleaning can be arranged when quoting."},{q:"Can you reach every upper storey window?", a:"Not necessarily. We assess access and safety before confirming the scope."}]},
  { slug:"commercial-exterior-cleaning-mitchell-shire", shortTitle:"Commercial Exterior Cleaning", title:"Commercial Exterior Cleaning in Mitchell Shire", priority:7, icon:"▤", summary:"Flexible exterior cleaning programs for offices, retail, facilities and managed properties.", intro:"Clean exterior areas help customers, visitors and staff feel confident in your premises. We provide one time and recurring exterior cleaning for suitable commercial properties across Kilmore and the Mitchell Shire.", method:"Every commercial site is scoped around access, public traffic, operating hours, surface types and safety controls. We agree on timing, isolate the work area where necessary and nominate the appropriate method for each surface. One local contact coordinates the job from quote through completion.", benefits:["Maintain a professional first impression","Schedule around site operations","Combine multiple exterior services","Arrange one time or recurring work"], includes:["Hard surface pressure cleaning","Building and facade washing","Gutter and window cleaning","site specific maintenance plans"], surfaces:["Retail and office exteriors","aged care and managed facilities","Body corporate common areas","Commercial paths and entries"], faqs:[{q:"Can work happen outside business hours?", a:"Yes, subject to the site and service. We can discuss timing that reduces disruption."},{q:"Do you offer recurring maintenance?", a:"Yes. Suitable sites can be placed on a practical periodic cleaning schedule."},{q:"Can you provide several services in one visit?", a:"Yes. We can scope a combined exterior cleaning visit across compatible services."}]},
];

const submenuServices: Service[] = [
  {slug:"delicate-surface-softwashing-kilmore",shortTitle:"Delicate Surface Softwashing",title:"Delicate Surface Softwashing in Kilmore & Mitchell Shire",priority:8,icon:"◌",summary:"Controlled low-pressure washing for render, painted finishes, cladding and other sensitive exterior surfaces.",intro:"Some exterior finishes need treatment and dwell time rather than force. Delicate surface softwashing targets organic growth and general grime while keeping water pressure appropriate for the material and coating.",method:"We inspect the substrate, coating, age, access, nearby plants and water-sensitive areas before selecting a suitable treatment. Products are applied at controlled strength, given the appropriate dwell time and rinsed gently. Test areas and targeted agitation may be used where the finish requires extra care.",benefits:["Clean sensitive finishes with controlled pressure","Treat mould and algae at the source","Reduce the risk of surface damage","Refresh detailed exterior areas"],includes:["Surface and coating assessment","Low-pressure treatment and rinse","Protection of nearby plants and fixtures","Targeted agitation where suitable"],surfaces:["Rendered walls","Painted cladding","Weatherboards","Decorative exterior finishes"],faqs:[{q:"Is softwashing completely pressure free?",a:"No. Water is still used, but at controlled low pressure suited to the surface rather than concrete-cleaning pressure."},{q:"Can every painted surface be softwashed?",a:"No. Failing paint, oxidation and fragile coatings need assessment before any cleaning method is confirmed."},{q:"Will it remove mould and algae?",a:"Softwashing is designed to treat organic growth, although heavily stained or deteriorated finishes may not return to an as-new appearance."}]},
  {slug:"exterior-gutter-washing-kilmore",shortTitle:"Exterior Gutter, Fascia & Eave Washing",title:"Exterior Gutter, Fascia & Eave Washing in Kilmore & Mitchell Shire",priority:9,icon:"⌁",summary:"Softwashing for visible gutter faces, fascia, eaves and roofline trims.",intro:"Visible gutter faces, fascia and eaves collect cobwebs, traffic film, mould and airborne grime. Exterior gutter washing improves the roofline presentation without being confused with debris removal from inside the gutter.",method:"We assess coatings, oxidation, access and surrounding surfaces before applying a suitable low-pressure wash. Visible gutter faces, fascia and accessible eaves are treated and rinsed carefully, with expectations set for permanent staining, faded paint and oxidation.",benefits:["Brighten the visible roofline","Remove cobwebs and surface grime","Use a coating-aware low-pressure method","Combine easily with house washing"],includes:["Visible gutter-face washing","Accessible fascia and eaves","Cobweb removal","Controlled rinse and tidy-up"],surfaces:["Colorbond gutter faces","Painted fascia","Eaves and soffits","Accessible roofline trims"],faqs:[{q:"Does this clean inside the gutters?",a:"No. Internal gutter debris removal is a separate service and can be added to the same quote."},{q:"Will old gutters look new again?",a:"Cleaning can improve grime and organic growth, but it cannot reverse fading, oxidation or coating failure."},{q:"Can this be added to a house wash?",a:"Yes. It is commonly quoted together with exterior wall washing."}]},
  {slug:"fence-washing-kilmore",shortTitle:"Fence Washing",title:"Fence Washing in Kilmore & Mitchell Shire",priority:10,icon:"▥",summary:"Surface-appropriate washing for Colorbond, painted and suitable masonry fencing.",intro:"Fences collect dust, mould, algae, cobwebs and splashback that can dull the boundary of an otherwise tidy property. We choose a cleaning method suited to the fence material and finish.",method:"The fence material, coating, stability, neighbouring property and surrounding gardens are checked first. Colorbond and painted fences are cleaned gently, while suitable masonry sections may receive controlled pressure cleaning. Runoff and overspray are managed throughout.",benefits:["Improve street and garden presentation","Match the method to the fence material","Remove organic growth and surface grime","Coordinate with a wider exterior clean"],includes:["Fence material assessment","Appropriate wash or treatment","Accessible posts and panels","Final rinse and work-area tidy"],surfaces:["Colorbond fencing","Painted fencing","Brick boundary walls","Suitable masonry fencing"],faqs:[{q:"Do you pressure wash Colorbond fences?",a:"We use a gentler method appropriate to coated steel rather than treating it like concrete."},{q:"Can you clean both sides?",a:"Yes where access and permission allow. The quoted scope will state which sides are included."},{q:"Will cleaning remove faded patches?",a:"No. Cleaning removes surface contamination but cannot restore weathered or damaged coatings."}]},
  {slug:"roof-softwashing-kilmore",shortTitle:"Roof Softwashing",title:"Roof Softwashing in Kilmore & Mitchell Shire",priority:11,icon:"⌃",summary:"A controlled wash process for suitable tile and Colorbond roofs requiring a more immediate clean.",intro:"Roof softwashing combines an appropriate cleaning treatment with controlled application and rinsing for roofs suited to an immediate cleaning process. Material, coating condition and access determine whether this method is appropriate.",method:"We assess pitch, access, roof material, coating, drainage, rainwater tanks and surrounding property. Suitable treatment is applied at controlled strength and rinsed according to the roof system and job plan. Runoff, tank connections and nearby plants are managed carefully.",benefits:["Achieve a more immediate visual clean","Use a roof-material-specific process","Treat organic growth and grime","Plan carefully for tanks and runoff"],includes:["Roof and access assessment","Controlled softwash application","Material-appropriate rinse","Runoff and property protection plan"],surfaces:["Suitable Colorbond roofing","Concrete roof tiles","Selected terracotta tiles","Compatible roof coatings"],faqs:[{q:"Is roof softwashing the same as pressure washing?",a:"No. It relies on suitable treatment and controlled low pressure rather than aggressive high-pressure cleaning."},{q:"Is every roof suitable?",a:"No. Roof condition, coating, pitch and access must be assessed first."},{q:"What if I have rainwater tanks?",a:"Tank connections and runoff are addressed in the job plan before treatment begins."}]},
  {slug:"roof-treatment-kilmore",shortTitle:"Roof Treatment",title:"Roof Treatment in Kilmore & Mitchell Shire",priority:12,icon:"⌃",summary:"Targeted biocide treatment for moss, lichen and algae that works gradually with weathering.",intro:"A roof treatment is a lower-disturbance option for suitable moss, lichen and algae growth. Rather than producing an instant fully rinsed result, the treatment continues working and the weather gradually releases dead organic material.",method:"We identify the roof material, growth, condition, drainage and tank connections before applying an appropriate treatment. Application is controlled to the affected areas, with runoff and overspray managed. We explain the expected change over time and whether follow-up assessment is appropriate.",benefits:["Treat moss, lichen and algae","Avoid unnecessary aggressive cleaning","Use a gradual weather-assisted process","Set clear expectations for timing"],includes:["Roof and growth assessment","Targeted biocide application","Tank and runoff planning","Aftercare and timing guidance"],surfaces:["Concrete roof tiles","Terracotta tiles where suitable","Selected coated roofing","Growth-affected roof areas"],faqs:[{q:"Will the roof look clean immediately?",a:"Not usually. A treatment works over time, with weather gradually releasing treated organic growth."},{q:"How is this different from roof softwashing?",a:"Softwashing is generally chosen for a more immediate cleaned result, while a treatment is designed to work progressively."},{q:"Can treatment be applied near rainwater tanks?",a:"Tank isolation and runoff controls must be planned before application."}]},
  {slug:"driveway-concrete-path-cleaning-kilmore",shortTitle:"Driveway, Concrete & Path Cleaning",title:"Driveway, Concrete & Path Cleaning in Kilmore & Mitchell Shire",priority:13,icon:"≈",summary:"Professional pressure cleaning for driveways, concrete paths, entrances and exposed aggregate.",intro:"Driveways and paths accumulate tyre marks, dirt, organic growth and general weathering. Professional surface cleaning restores a more even finish and improves the presentation of the areas people notice first.",method:"We identify the concrete type, age, existing coating, drainage and stain profile before selecting pressure, treatment and nozzle technique. Large areas are cleaned in controlled overlapping passes, with edges detailed and runoff managed.",benefits:["Refresh driveways and entrances","Produce a more consistent finish","Treat organic growth and general grime","Prepare suitable concrete for sealing"],includes:["Driveways and parking areas","Concrete paths and entrances","Exposed aggregate by assessment","Edge detailing and rinse-down"],surfaces:["Plain concrete","Exposed aggregate","Coloured concrete by assessment","Concrete paths and steps"],faqs:[{q:"Can all stains be removed?",a:"No. Oil, rust, paint and deeply absorbed marks may improve without disappearing completely."},{q:"Can older concrete be damaged?",a:"Weak or deteriorated concrete requires lower pressure and careful expectations, which is why we assess it first."},{q:"Can you seal it afterwards?",a:"Yes, suitable surfaces can be quoted for sealing after cleaning and adequate drying."}]},
  {slug:"paver-pool-surround-cleaning-kilmore",shortTitle:"Paver & Pool Surround Cleaning",title:"Paver & Pool Surround Cleaning in Kilmore & Mitchell Shire",priority:14,icon:"▦",summary:"Controlled cleaning for pavers, patios and suitable pool surrounds.",intro:"Pavers and pool surrounds can become dark, slippery-looking and uneven as dirt and organic growth settle into joints and textured surfaces. We clean them with attention to the substrate, jointing material and nearby pool environment.",method:"We assess the paver type, joint stability, coatings, drainage and proximity to pool water before selecting equipment and treatment. Pressure is controlled to reduce unnecessary joint loss, and sensitive edges, fixtures and surrounding landscaping are protected.",benefits:["Refresh entertaining and pool areas","Use pressure suited to pavers and joints","Remove built-up surface grime","Prepare suitable pavers for sealing"],includes:["Paver and patio cleaning","Suitable pool-surround cleaning","Controlled edge and joint work","Final rinse and tidy-up"],surfaces:["Concrete pavers","Brick pavers","Selected natural stone","Textured pool surrounds"],faqs:[{q:"Will pressure cleaning remove jointing sand?",a:"Some loose jointing material may be displaced. We assess the joints and discuss any re-sanding requirement before work."},{q:"Can you clean next to pool water?",a:"Yes where suitable controls can protect the pool and surrounding equipment."},{q:"Can pavers be sealed afterwards?",a:"Suitable pavers can be assessed for cleaning, drying, re-sanding and sealing as a coordinated scope."}]},
  {slug:"retaining-wall-cleaning-kilmore",shortTitle:"Retaining Wall Cleaning",title:"Retaining Wall Cleaning in Kilmore & Mitchell Shire",priority:15,icon:"▤",summary:"Cleaning for suitable concrete, block, brick and rendered retaining walls.",intro:"Retaining walls often sit in damp, shaded areas where soil splash, algae and atmospheric grime build quickly. We select a method that accounts for the wall material, drainage and surrounding garden.",method:"The wall finish, structural condition, drainage, staining and nearby plants are assessed before cleaning. Suitable masonry may receive controlled pressure and treatment, while painted or rendered walls are handled with lower pressure and extra care.",benefits:["Improve garden and boundary presentation","Treat organic growth on shaded walls","Match pressure to the wall finish","Coordinate with paths and driveway cleaning"],includes:["Wall and finish assessment","Suitable cleaning treatment","Controlled pressure or softwash","Protection of nearby garden areas"],surfaces:["Concrete sleeper walls","Concrete and masonry block","Brick retaining walls","Rendered walls by assessment"],faqs:[{q:"Can you remove soil and mineral staining?",a:"Surface soil usually cleans well, while mineral movement and deep staining may only improve."},{q:"Will you use high pressure on render?",a:"No. Render requires a controlled low-pressure approach based on coating condition."},{q:"Can nearby plants be protected?",a:"Yes. Plant protection and runoff management form part of the job plan."}]},
];

export const serviceExpansionEnabled = process.env.NEXT_PUBLIC_SERVICE_EXPANSION_ENABLED === "true";

export const draftServices: Service[] = [
  {slug:"timber-cleaning-restoration-kilmore",shortTitle:"Timber Cleaning & Restoration",title:"Timber Cleaning & Restoration in Kilmore & Mitchell Shire",priority:4,icon:"▥",category:"exterior-cleaning",release:"draft",summary:"Careful cleaning and preparation for decks, fences and exterior timber, with staining or oiling available after assessment.",intro:"Exterior timber needs a different process from concrete. Our planned timber restoration service combines material-specific cleaning, controlled rinsing and preparation for a suitable protective finish.",method:"We identify the timber species, existing coating, weathering, fixings and surrounding surfaces before recommending a process. Cleaning products, agitation and water pressure are kept within timber-safe limits. Where staining or oiling is suitable, moisture, preparation and product compatibility are assessed before application.",benefits:["Restore tired exterior timber","Prepare suitable timber for a fresh finish","Avoid harsh concrete-cleaning methods","Match the process to the existing coating"],includes:["Timber condition assessment","Deck and fence cleaning","Coating and preparation advice","Staining or oiling by confirmed scope"],surfaces:["Timber decking","Exterior stairs and landings","Timber fences and screens","Suitable outdoor furniture by assessment"],faqs:[{q:"Is staining included with every timber clean?",a:"No. Cleaning and coating are assessed separately because timber condition, moisture and the existing finish determine what preparation is required."},{q:"Do you pressure wash timber?",a:"Timber may be rinsed with carefully controlled equipment, but it is never treated with the same settings or technique used on concrete."},{q:"Can you restore grey timber?",a:"Weathered timber can often be improved, but the result depends on species, age, coating history and deterioration. We set expectations after inspection."}]},
  {slug:"surface-sealing-kilmore",shortTitle:"Surface Sealing",title:"Concrete & Paver Sealing in Kilmore & Mitchell Shire",priority:5,icon:"◆",category:"exterior-cleaning",release:"draft",summary:"Cleaning, preparation and protective sealing for suitable concrete, exposed aggregate and paver surfaces.",intro:"Sealing can help protect suitable hard surfaces and improve ongoing maintenance after professional cleaning. Our planned sealing service focuses on correct preparation, compatible products and realistic finish expectations.",method:"The surface is assessed for existing coatings, moisture, contamination, efflorescence and damage. Cleaning and drying requirements are confirmed before a compatible sealer is selected. Application timing depends on weather, surface temperature and the manufacturer’s specification.",benefits:["Protect suitable porous surfaces","Make routine maintenance easier","Refresh the appearance of selected finishes","Combine cleaning and sealing under one scope"],includes:["Surface and coating assessment","Professional pre-cleaning by scope","Sealer compatibility recommendation","Controlled application and curing guidance"],surfaces:["Concrete","Exposed aggregate","Concrete pavers","Selected masonry surfaces"],faqs:[{q:"Can every surface be sealed?",a:"No. Existing coatings, moisture, contamination and the substrate condition may make sealing unsuitable until further preparation is completed."},{q:"Is sealing completed immediately after pressure washing?",a:"Usually not. The surface needs to be sufficiently clean and dry, and weather conditions must suit the selected product."},{q:"Will sealing stop all staining?",a:"No sealer makes a surface maintenance-free. A suitable product can improve protection and cleanability, but spills and organic growth still need attention."}]},
  {slug:"complete-exterior-maintenance-kilmore",shortTitle:"Complete Exterior Maintenance",title:"Complete Exterior Maintenance in Kilmore & Mitchell Shire",priority:6,icon:"✓",category:"complete-exterior-maintenance",release:"draft",relatedServices:["gutter-cleaning-kilmore","solar-panel-cleaning-kilmore","basic-window-cleaning-kilmore"],summary:"One coordinated maintenance solution for gutters, solar panels and exterior windows, available individually or as a scheduled package.",intro:"Keeping the smaller exterior maintenance jobs together makes property care easier to organise. Our planned maintenance solution combines gutter clearing, gentle solar panel cleaning and routine exterior window cleaning under one coordinated visit or schedule.",method:"We assess access, roof conditions, glazing, solar arrays and drainage before confirming the package. Each component keeps its own appropriate method and safety limits. Services can be booked individually, combined for one visit or scheduled periodically where the property is suitable.",benefits:["Coordinate three recurring maintenance jobs","Reduce repeat bookings and site visits","Choose individual services or a package","Create a practical seasonal schedule"],includes:["Gutter cleaning and flow checks","Gentle solar panel cleaning","Routine exterior window cleaning","Optional recurring maintenance plan"],surfaces:["Residential gutter systems","Suitable solar arrays","Accessible exterior glazing","Suitable commercial properties by quote"],faqs:[{q:"Do I have to book all three services?",a:"No. Gutter, solar panel and window cleaning remain available individually. The package is for customers who want them coordinated."},{q:"Can this be scheduled automatically?",a:"Suitable properties can be placed on an agreed seasonal or periodic maintenance schedule."},{q:"Can house washing be added?",a:"Yes. House washing and other compatible exterior services can be added to the same quotation where practical."}]},
];

const expandedPrimarySlugs=["house-washing-kilmore","roof-cleaning-kilmore","surface-pressure-washing-kilmore","timber-cleaning-restoration-kilmore","surface-sealing-kilmore","complete-exterior-maintenance-kilmore","commercial-exterior-cleaning-mitchell-shire"];
const surfaceSealing=draftServices.find(service=>service.slug==="surface-sealing-kilmore")!;
export const allServices:Service[]=[...currentServices,...submenuServices,...draftServices];
export const routableServices:Service[]=serviceExpansionEnabled?allServices:[...currentServices,...submenuServices,surfaceSealing];
export const services:Service[]=serviceExpansionEnabled?expandedPrimarySlugs.map(slug=>allServices.find(service=>service.slug===slug)!).filter(Boolean):currentServices;

export const serviceCategories=[
  {
    slug:"exterior-washing",
    title:"Exterior Washing",
    href:"/services#exterior-washing",
    summary:"Gentle, surface-appropriate washing for homes and exterior finishes.",
    items:["House softwashing","Delicate surface softwashing","Exterior gutters, fascia and eaves","Fence washing","Basic window cleaning"],
    serviceSlugs:["house-washing-kilmore","delicate-surface-softwashing-kilmore","exterior-gutter-washing-kilmore","fence-washing-kilmore","basic-window-cleaning-kilmore"],
  },
  {
    slug:"roof-gutter-solar",
    title:"Roof, Gutter & Solar",
    href:"/services#roof-gutter-solar",
    summary:"Roof care and routine maintenance for the areas above your home.",
    items:["Roof softwashing","Roof treatments","Internal gutter cleaning","Solar panel cleaning"],
    serviceSlugs:["roof-softwashing-kilmore","roof-treatment-kilmore","gutter-cleaning-kilmore","solar-panel-cleaning-kilmore"],
  },
  {
    slug:"pressure-cleaning-sealing",
    title:"Pressure Cleaning & Sealing",
    href:"/services#pressure-cleaning-sealing",
    summary:"Professional cleaning and protection for hard outdoor surfaces.",
    items:["Driveways, concrete and paths","Pavers and pool surrounds","Retaining walls","Concrete and paver sealing"],
    serviceSlugs:["driveway-concrete-path-cleaning-kilmore","paver-pool-surround-cleaning-kilmore","retaining-wall-cleaning-kilmore","surface-sealing-kilmore"],
  },
] as const;

export const enquiryServices=[
  "House & Exterior Washing",
  "Exterior Gutters, Fascia & Eaves",
  "Roof Cleaning or Treatment",
  "Internal Gutter Cleaning",
  "Pressure Cleaning",
  "Surface Sealing",
  "Solar Panel Cleaning",
  "Basic Window Cleaning",
] as const;
export const priorityServices = services.slice(0,3);
export function getService(slug:string){return routableServices.find(service=>service.slug===slug)}
