export const serviceAreas = [
  {slug:"kilmore",name:"Kilmore",region:"Mitchell Shire",intro:"Based locally in Kilmore, we provide responsive exterior cleaning for established homes, new estates, rural properties and businesses throughout the township.",detail:"Kilmore properties experience a mix of winter damp, dust, mature trees and fast-changing regional weather. That makes regular attention to roofs, gutters, walls and hard surfaces especially worthwhile."},
  {slug:"wallan",name:"Wallan",region:"Mitchell Shire",intro:"We service homes, investment properties and commercial sites throughout Wallan with practical exterior-cleaning options and flexible scheduling.",detail:"Wallan’s rapid growth means we work across newer estates, established homes and acreage properties. Each site receives a surface and access assessment before a method is recommended."},
  {slug:"seymour",name:"Seymour",region:"Mitchell Shire",intro:"Our team travels to Seymour for residential and suitable commercial exterior cleaning, from house washing and roofs to driveways and gutters.",detail:"Heat, dust, trees and seasonal organic growth all influence how Seymour properties weather. We tailor cleaning to the coating, surface condition and surrounding environment."},
  {slug:"broadford",name:"Broadford",region:"Mitchell Shire",intro:"SS Exterior Services provides professional exterior cleaning across Broadford and nearby rural localities.",detail:"Broadford’s combination of township and rural properties calls for flexible access planning and equipment. We regularly assist with complete exterior refreshes and individual maintenance services."},
  {slug:"lancefield",name:"Lancefield",region:"Macedon Ranges",intro:"We service Lancefield properties by arrangement, offering the same careful exterior-cleaning methods used throughout our core Mitchell Shire area.",detail:"Older homes, gardens and tree cover can produce distinctive maintenance needs. We assess sensitive finishes and surrounding landscaping before work starts."},
  {slug:"mitchell-shire",name:"Mitchell Shire",region:"Regional Victoria",intro:"From Kilmore and Wallan to Broadford, Seymour and surrounding communities, we provide exterior cleaning across Mitchell Shire and beyond.",detail:"Our regional service is built around reliable communication, appropriate equipment and cleaning methods selected for the actual property—not generic packages."},
];

export const posts = [
  {slug:"how-often-clean-gutters-kilmore",title:"How Often Should You Clean Gutters in Kilmore?",description:"A practical guide to gutter-cleaning frequency for regional Victorian homes.",date:"2026-08-09",category:"Gutter Cleaning",body:["There is no single gutter-cleaning interval that suits every home. A relatively open property may need attention once or twice a year, while a house surrounded by mature gums can fill much faster.","The most useful approach is to inspect gutters after heavy leaf fall and before periods of sustained rain. Overflow marks, plants growing from the gutter, water spilling behind fascia and downpipes that do not discharge normally are all signs that attention is overdue.","Regular cleaning is usually simpler and less expensive than responding after water has reached eaves, walls or foundations. If safe access is uncertain, use a properly equipped professional rather than working from a ladder."],faqs:[]},
  {slug:"soft-washing-vs-pressure-washing",title:"Soft Washing vs Pressure Washing: What’s the Difference?",description:"Why exterior walls, roofs and concrete need different cleaning methods.",date:"2026-08-09",category:"House Washing",body:["Soft washing and pressure washing solve different problems. Pressure washing uses controlled water pressure to lift soil and growth from durable flat surfaces such as concrete and many pavers.","Soft washing relies on an appropriate cleaning treatment, dwell time and a lower-pressure rinse. It is commonly better suited to painted walls, cladding, render and many roof-cleaning situations.","The surface—not the machine—should determine the method. Coating condition, material, access, organic growth and surrounding plants all need to be considered before work begins."],faqs:[]},
  {slug:"roof-biocide-treatment-explained",title:"What Is a Roof Biocide Treatment?",description:"How roof biocide treatments work and when they may be suitable.",date:"2026-08-09",category:"Roof Cleaning",body:["A roof biocide treatment targets moss, lichen and algae and may continue working after application. Unlike a dramatic same-day pressure clean, the visible result can develop progressively as weather removes treated growth.","Whether it is suitable depends on roof material, condition, pitch, access and nearby rainwater systems. Colorbond, terracotta and concrete tile do not share one universal cleaning process.","A professional assessment should also account for runoff, water tanks, gutters, gardens and manufacturer guidance. Customers should receive realistic expectations about the treatment timeline."],faqs:[]},
];
