import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { Footer, Header, QuoteForm } from "../../components";
import { getService, services } from "../data";
import { getPublishedRecord } from "../../../lib/content";

export function generateStaticParams(){return services.map(service=>({slug:service.slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const service=getService(slug);if(!service)return{};const managed=await getPublishedRecord("service", slug);const title=managed?.seo_title||managed?.title||service.title;const description=managed?.seo_description||managed?.excerpt||`${service.summary} Servicing Kilmore, Wallan, Seymour, Broadford and Mitchell Shire. Get a free quote.`;return{title, description, alternates:{canonical:`/services/${slug}`}, openGraph:{title, description, url:`/services/${slug}`}}}

export default async function ServicePage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const service=getService(slug);if(!service)notFound();const managed=await getPublishedRecord("service", slug);const display={...service, title:managed?.title||service.title, summary:managed?.excerpt||service.summary, intro:String(managed?.body?.content||service.intro)};const showResults=slug.includes("gutter")||slug.includes("pressure")||slug.includes("roof");
  const schema={"@context":"https://schema.org","@graph":[{"@type":"Service","@id":`https://ssexteriorservices.com.au/services/${slug}#service`, name:display.title, description:display.summary, serviceType:display.shortTitle, provider:{"@type":["LocalBusiness","HomeAndConstructionBusiness"],"@id":"https://ssexteriorservices.com.au/#business", name:"SS Exterior Services", telephone:"+61447130743", email:"ssexteriorservices@outlook.com"}, areaServed:["Kilmore","Mitchell Shire","Wallan","Seymour","Broadford","Lancefield"]},{"@type":"FAQPage", mainEntity:display.faqs.map(f=>({"@type":"Question", name:f.q, acceptedAnswer:{"@type":"Answer", text:f.a}}))}]};
  return <><Header/><main><section className="service-hero"><div className="shell service-hero-grid"><div><div className="breadcrumbs"><Link href="/">Home</Link><span>/</span><Link href="/#services">Services</Link><span>/</span><b>{display.shortTitle}</b></div><h1>{display.title}</h1><p>{display.intro}</p><div className="hero-actions"><a className="button" href="#service-quote">Get a free quote <span>→</span></a><a className="text-link light-link" href="tel:0447130743">0447 130 743</a></div></div><div className="service-mark"><span>{display.icon}</span><small>Priority {display.priority}<br/>service</small></div></div></section>
  <section className="service-content section shell"><article><p className="eyebrow">Our approach</p><h2>The method follows the surface.</h2><p>{service.intro}</p><p>{service.method}</p><h2>What’s included</h2><div className="check-grid">{service.includes.map(item=><span key={item}>✓ {item}</span>)}</div><h2>Suitable surfaces</h2><div className="surface-tags">{service.surfaces.map(item=><span key={item}>{item}</span>)}</div></article><aside><p className="eyebrow">At a glance</p><h3>Why book this service?</h3>{service.benefits.map(item=><p key={item}>✓ {item}</p>)}<a className="button dark" href="#service-quote">Request a quote</a></aside></section>
  {showResults&&<section className="before-after section"><div className="shell"><div className="section-heading"><div><p className="eyebrow">Recent work</p><h2>See the difference.</h2></div><p>Real project photography from SS Exterior Services.</p></div><div className="result-pair wide"><figure><img src={slug.includes("roof")?"/images/facebook-roof-result-1.jpg":slug.includes("gutter")?"/images/gutter-before.jpg":"/images/pressure-before.jpg"} alt={`${service.shortTitle} project result`}/><figcaption>{slug.includes("roof")?"Roof result one":"Before"}</figcaption></figure><figure><img src={slug.includes("roof")?"/images/facebook-roof-result-2.jpg":slug.includes("gutter")?"/images/gutter-after.jpg":"/images/pressure-after.jpg"} alt={`${service.shortTitle} completed result`}/><figcaption>{slug.includes("roof")?"Roof result two":"After"}</figcaption></figure></div></div></section>}
  <section className="faq section shell"><div><p className="eyebrow">Common questions</p><h2>Good to know.</h2></div><div>{service.faqs.map(f=><details key={f.q}><summary>{f.q}<span>+</span></summary><p>{f.a}</p></details>)}</div></section>
  <section className="local-copy section"><div className="shell"><p className="eyebrow light">Proudly local</p><h2>{service.shortTitle} across Kilmore and the region.</h2><p>Based in Kilmore, we service properties throughout Wallan, Broadford, Seymour, Lancefield, Pyalong, Wandong and surrounding communities. Regional properties face dust, mature trees and changing weather, so we tailor the process to the site.</p><p><Link className="text-link light-link" href="/service-areas">Explore all service areas →</Link></p></div></section>
  <section className="quote-section section" id="service-quote"><div className="shell quote-grid"><div><p className="eyebrow light">Free, straightforward quote</p><h2>Let’s get your {service.shortTitle.toLowerCase()} sorted.</h2><p>Send the details and Simon will get back to you. No automated runaround and no pushy sales.</p><a className="quote-phone" href="tel:0447130743"><small>Call Simon</small>0447 130 743</a></div><QuoteForm defaultService={service.shortTitle}/></div></section>
  <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/></main><Footer/></>}
