insert into public.website_content (content_type,slug,title,excerpt,body,status,sort_order) values
('page','about','Local knowledge. Honest advice. Work we stand behind.','Based in Kilmore and run by Simon, SS Exterior Services helps homeowners and businesses maintain cleaner, better-presented properties across Mitchell Shire and surrounding communities.',jsonb_build_object('content','SS Exterior Services began with a straightforward goal: make exterior property maintenance easier for local residents. What started as hands-on work for nearby homeowners has grown through repeat customers, referrals and a reputation for showing up prepared.\n\nSimon remains closely involved—from the first conversation and site assessment through to the final walkthrough. Customers receive clear advice from someone who understands the work, rather than a generic sales process.\n\nWe service established homes, newer estates, rural properties and suitable commercial sites. The same attention goes into planning access, choosing the method and protecting the property.'),'published',1),
('service','house-washing-kilmore','House Washing in Kilmore & Mitchell Shire','Surface-appropriate soft washing for cladding, render, brick, eaves and exterior walls.',jsonb_build_object('content','Dust, mould, algae, cobwebs and traffic film gradually dull a home’s exterior. Our house washing service restores a cleaner finish using a method selected for the actual wall system.'),'published',1),
('service','roof-cleaning-kilmore','Roof Cleaning & Biocide Treatment in Kilmore','Roof soft washing and biocide treatments tailored to tile and Colorbond roofing.',jsonb_build_object('content','Moss, lichen, algae and airborne grime can make roofing look tired and hold moisture against the surface. We provide considered roof-cleaning options for suitable tile and Colorbond roofs.'),'published',2),
('service','surface-pressure-washing-kilmore','Surface Pressure Washing in Kilmore & Mitchell Shire','Professional cleaning for driveways, paths, patios, exposed aggregate, pavers and decks.',jsonb_build_object('content','Flat outdoor surfaces collect traffic film, soil, organic growth, tyre marks and staining. We use professional equipment and surface-specific preparation to produce a consistent clean.'),'published',3),
('service','gutter-cleaning-kilmore','Gutter Cleaning in Kilmore & Mitchell Shire','Remove leaves, mud and debris so gutters and downpipes can drain properly.',jsonb_build_object('content','Blocked gutters can overflow into eaves, walls and foundations. Our gutter cleaning service removes built-up leaves, mud, nests and debris.'),'published',4),
('service','solar-panel-cleaning-kilmore','Solar Panel Cleaning in Kilmore & Mitchell Shire','Gentle panel cleaning based on manufacturer-safe water, tools and access practices.',jsonb_build_object('content','Dust, pollen, bird droppings and regional airborne grime can build up across solar arrays. We clean suitable systems without abrasive blades, harsh chemicals or inappropriate pressure.'),'published',5),
('service','basic-window-cleaning-kilmore','Basic Window Cleaning in Kilmore & Mitchell Shire','Straightforward residential and commercial glass cleaning for a clearer finish.',jsonb_build_object('content','Our basic window cleaning service is designed for routine dirt, dust and light marks on accessible residential and commercial glazing.'),'published',6),
('service','commercial-exterior-cleaning-mitchell-shire','Commercial Exterior Cleaning in Mitchell Shire','Flexible exterior-cleaning programs for offices, retail, facilities and managed properties.',jsonb_build_object('content','Clean exterior areas help customers, visitors and staff feel confident in your premises. We provide one-off and recurring exterior cleaning for suitable commercial properties.'),'published',7)
on conflict(content_type,slug) do nothing;
